---
- src: git@gitlab.fast-servers.eu:galaxy-roles/vmware.guest.git
  scm: git
  version: "develop"
  name: vmware.guest

- src: git@gitlab.fast-servers.eu:galaxy-roles/base.vm.git
  scm: git
  version: "master"
  name: base.vm

- src: git@gitlab.fast-servers.eu:galaxy-roles/configure.docker.git
  scm: git
  version: "master"
  name: configure.docker

- src: git@gitlab.fast-servers.eu:galaxy-roles/configure.kubernetes.git
  scm: git
  version: "master"
  name: configure.kubernetes

- src: git@gitlab.fast-servers.eu:galaxy-roles/commons.git
  scm: git
  version: "master"
  name: commons

- src: git@gitlab.fast-servers.eu:galaxy-roles/configure.cni.git
  scm: git
  version: "master"
  name: configure.cni

- src: git@gitlab.fast-servers.eu:galaxy-roles/base.packages.git
  scm: git
  version: "master"
  name: base.packages
