---
- src: git@github.com:pmozdzynski/vmware.guest.git
  scm: git
  version: "develop"
  name: vmware.guest

- src: git@github.com:pmozdzynski/base.vm.git
  scm: git
  version: "master"
  name: base.vm

- src: git@github.com:pmozdzynski/configure.docker.git
  scm: git
  version: "master"
  name: configure.docker

- src: git@github.com:pmozdzynski/configure.kubernetes.git
  scm: git
  version: "master"
  name: configure.kubernetes

- src: git@github.com:pmozdzynski/commons.git
  scm: git
  version: "master"
  name: commons

- src: git@github.com:pmozdzynski/configure.cni.git
  scm: git
  version: "master"
  name: configure.cni
