---
- src: git@gitlab.fast-servers.eu:galaxy-roles/vmware.guest.git
  scm: git
  version: "develop"
  name: vmware.guest

- src: git@gitlab.fast-servers.eu:galaxy-roles/base.vm.git
  scm: git
  version: "master"
  name: base.vm
