---

- hosts: '{{ limit_hostgroup }}'
  gather_facts: no
  connection: local
  become: no
  vars:
    vmguest_wait_for_ip_address: yes

  roles:
    - { role: vmware.guest, when: "use_vcenter == 'true'" }

- hosts: '{{ limit_hostgroup }}'
  gather_facts: '{{ newinstall }}'
  become: yes
  vars:
    yumrepo_manage: True
#  ignore_errors: true
  roles:
    - { role: base.vm, when: "newinstall == 'true' and (ansible_local.build_completed.general.completed != 'true')" }
  tasks:
    - debug: msg="{{ ansible_local.build_completed }}"

- hosts: kubernetz
  gather_facts: yes
  become: yes
  roles:
    - { role: configure.docker, tags: docker }

- hosts: kubernetz
  service:
    name: firewalld
    state: stopped
    enabled: no

- hosts: k8s_master
  gather_facts: yes
  become: yes
  roles:
    - { role: configure.kubernetes/master, tags: master }
    - { role: configure.cni, tags: cni }

- hosts: k8s_node
  gather_facts: yes
  become: yes
  roles:
    - { role: configure.kubernetes/node, tags: node }

- hosts: k8s_master
  gather_facts: yes
  become: yes
  tasks:
    - name: "Helm role"
      include_role:
        name: helm
      when: "additional_features.helm"
      run_once: yes
      tags: helm

    - name: "MetalLB role"
      include_role:
        name: metallb
      when: "additional_features.metallb"
      run_once: yes
      tags: metallb

    - name: "Healthcheck role"
      include_role:
        name: healthcheck
      when: "additional_features.healthcheck"
      run_once: yes
      tags: healthcheck
